"""Advertise version and feature flags so agents detect a stale MCP server."""

from __future__ import annotations

from typing import Any

from hardly import __version__

# Bump when tools/features change in a way agents must notice.
FEATURES = (
    "forms",
    "ui",
    "labels",
    "routes",
    "around",
    "brief",
    "story",
    "stub",
    "correlate",
    "trace",
    "cookies",
    "secrets",
    "credentials",
    "cookie_flags",
    "identity_fields",
    "oauth_signals",
    "value_shapes_index",
    "credentials_diff",
    "recipe_login_seed",
    "html_autocomplete",
    "oauth_flow",
    "entry_shapes",
    "diff",
    "recipe_plan",
    "find_search",
    "grids",
    "replay_check",
    "crawl_robots",
    "crawl",
    "arcgis_explore",
    "arcgis",
    "data_attrs",
    "challenges",
    "redirects",
    "issues",
    "recommend",
    "modes",
    "discover",
    "tree",
    "params",
    "graphql",
    "content_classify",
    "outline",
    "capture_aria",
    "capture_aria_ref",
    "capture_screenshot",
    "capture_trace",
    "capture_doctor",
    "duplicates",
    "slow",
    "wall",
    "pages",
    "stats",
    "reopen",
    "webforms",
    "help",
    "openapi_security",
    "cli_parity",
    "preferred_host",
    "preferred_host_cdn_skip",
    "related_hosts",
    "export_postman",
    "export_brief",
    "coverage",
    "body_backfill",
    "truncated_token",
    "capture_elements",
    "capture_click",
    "capture_fill",
    "capture_press",
    "capture_url",
    "capture_recipe",
    "offline_xpath",
)

TOOLS = (
    "hardly_capabilities",
    "hardly_modes",
    "hardly_mode",
    "hardly_help",
    "hardly_open",
    "hardly_reopen",
    "hardly_list_sessions",
    "hardly_close",
    "hardly_summary",
    "hardly_stats",
    "hardly_coverage",
    "hardly_hosts",
    "hardly_endpoints",
    "hardly_search",
    "hardly_entry",
    "hardly_forms",
    "hardly_ui",
    "hardly_routes",
    "hardly_around",
    "hardly_brief",
    "hardly_story",
    "hardly_stub",
    "hardly_correlate",
    "hardly_trace",
    "hardly_cookies",
    "hardly_secrets",
    "hardly_credentials",
    "hardly_diff",
    "hardly_recipe_plan",
    "hardly_find_search",
    "hardly_grids",
    "hardly_replay_check",
    "hardly_crawl",
    "hardly_arcgis_explore",
    "hardly_arcgis",
    "hardly_data_attrs",
    "hardly_challenges",
    "hardly_redirects",
    "hardly_issues",
    "hardly_recommend",
    "hardly_tree",
    "hardly_params",
    "hardly_graphql",
    "hardly_content",
    "hardly_outline",
    "hardly_duplicates",
    "hardly_slow",
    "hardly_wall",
    "hardly_pages",
    "hardly_compare_entries",
    "hardly_auth",
    "hardly_flow",
    "hardly_schema",
    "hardly_sql",
    "hardly_export_md",
    "hardly_export_openapi",
    "hardly_export_postman",
    "hardly_export_brief",
    "hardly_curl",
    "hardly_probe",
    "hardly_capture_start",
    "hardly_capture_stop",
    "hardly_capture_goto",
    "hardly_capture_elements",
    "hardly_capture_click",
    "hardly_capture_fill",
    "hardly_capture_press",
    "hardly_capture_url",
    "hardly_capture_aria",
    "hardly_capture_screenshot",
    "hardly_capture_recipe",
    "hardly_capture_list",
    "hardly_capture_status",
    "hardly_capture_once",
    "hardly_discover",
    "hardly_capture_doctor",
)


def capabilities() -> dict[str, Any]:
    capture_ok = False
    playwright: dict[str, Any] = {"package": False, "ready": False}
    try:
        from hardly.capture import playwright_status

        playwright = playwright_status()
        capture_ok = bool(playwright.get("ready"))
    except Exception as exc:  # noqa: BLE001
        playwright = {"package": False, "ready": False, "error": str(exc)}
    from hardly.core.modes import list_modes

    return {
        "name": "hardly",
        "version": __version__,
        "features": list(FEATURES),
        "tools": list(TOOLS),
        "tool_count": len(TOOLS),
        "modes": list_modes()["modes"],
        "capture_available": capture_ok,
        "playwright": playwright,
        "next": (
            "Pick a mode with hardly_modes / hardly_mode. "
            "If this tool list is missing expected names (e.g. hardly_modes, "
            "hardly_discover), restart the hardly MCP server. "
            "If capture_available is false, see playwright.hint / "
            "hardly_capture_doctor."
        ),
    }
