"""Write a portal RE brief as Markdown."""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

from hardly.core.brief import portal_brief


def export_brief_md(
    conn: sqlite3.Connection,
    output_path: str | Path,
    *,
    har_path: str | Path | None = None,
    host: str | None = None,
) -> dict[str, Any]:
    """Render portal_brief to a Markdown file on disk."""
    brief = portal_brief(conn, har_path=har_path, host=host)
    if brief.get("error"):
        return brief

    lines: list[str] = []
    h = brief.get("host") or "portal"
    lines.append(f"# Portal brief ({h})")
    lines.append("")
    lines.append("Generated by hardly. Secrets omitted; treat the HAR as confidential.")
    lines.append("")
    lines.append(f"- Steps: **{brief.get('step_count')}**")
    roles = brief.get("roles") or {}
    if roles:
        lines.append(
            "- Roles: "
            + ", ".join(f"{k}={v}" for k, v in sorted(roles.items()))
        )
    cov = brief.get("coverage") or {}
    if cov.get("entries"):
        lines.append(
            f"- Body preview ratio: **{cov.get('preview_ratio')}** "
            f"({cov.get('with_preview')}/{cov.get('entries')})"
        )
    kinds = brief.get("content_kinds") or {}
    if kinds:
        lines.append(
            "- Content kinds: "
            + ", ".join(f"{k}={v}" for k, v in list(kinds.items())[:12])
        )
    lines.append("")

    if kinds:
        lines.append("## Content kinds")
        lines.append("")
        for k, v in list(kinds.items())[:20]:
            lines.append(f"- **{k}**: {v}")
        samples = brief.get("content_samples") or {}
        for k, items in list(samples.items())[:8]:
            for item in items[:1]:
                hints = ", ".join((item.get("hints") or [])[:4])
                lines.append(
                    f"  - sample `{item.get('entry_id')}` `{item.get('path')}`"
                    + (f" ({hints})" if hints else "")
                )
        lines.append("")

    lines.append("## Story")
    lines.append("")
    for step in brief.get("steps") or []:
        role = step.get("role") or "?"
        content = step.get("content") or {}
        ck = content.get("kind") or step.get("response_kind") or "?"
        lines.append(
            f"- `{step.get('entry_id')}` **{step.get('method')}** "
            f"`{step.get('path')}` ({role}, {ck}, {step.get('status')})"
        )
        if content.get("table_headers"):
            lines.append(
                f"  - table headers: {', '.join(content['table_headers'][:12])}"
            )
        if content.get("json_keys"):
            lines.append(
                f"  - json keys: {', '.join(content['json_keys'][:16])}"
            )
        if content.get("columns"):
            lines.append(
                f"  - csv columns: {', '.join(content['columns'][:16])}"
            )
        if step.get("request_fields"):
            lines.append(f"  - request fields: {', '.join(step['request_fields'][:20])}")
        if step.get("forms"):
            for form in step["forms"][:2]:
                lines.append(
                    f"  - form → {form.get('method')} {form.get('action')} "
                    f"fields={form.get('field_names')}"
                )
        if step.get("handler_functions"):
            lines.append(
                f"  - handlers: {', '.join(step['handler_functions'][:10])}"
            )
    lines.append("")

    corrs = brief.get("correlations") or []
    if corrs:
        lines.append("## Correlations")
        lines.append("")
        for c in corrs[:20]:
            lines.append(
                f"- `{c.get('name_hint')}` entry {c.get('from_entry_id')} → "
                f"{c.get('to_entry_id')} ({c.get('to_where')})"
            )
        lines.append("")

    cookies_set = brief.get("cookie_names_set") or []
    cookies_sent = brief.get("cookie_names_sent") or []
    if cookies_set or cookies_sent:
        lines.append("## Cookies (names)")
        lines.append("")
        if cookies_set:
            lines.append(f"- Set: {', '.join(cookies_set)}")
        if cookies_sent:
            lines.append(f"- Sent: {', '.join(cookies_sent)}")
        lines.append("")

    forms = brief.get("form_pages") or []
    if forms:
        lines.append("## Forms")
        lines.append("")
        for page in forms[:10]:
            lines.append(
                f"- entry `{page.get('entry_id')}` `{page.get('path')}` "
                f"fields={page.get('field_names')}"
            )
        lines.append("")

    routes = brief.get("js_routes") or []
    if routes:
        lines.append("## JS routes")
        lines.append("")
        for r in routes[:20]:
            lines.append(
                f"- `{r.get('path')}` (score={r.get('score')}, n={r.get('count')})"
            )
        lines.append("")

    issues = brief.get("issues") or {}
    if issues.get("issue_count"):
        lines.append("## Issues")
        lines.append("")
        lines.append(f"- Count: {issues.get('issue_count')} by_kind={issues.get('by_kind')}")
        for issue in issues.get("sample") or []:
            lines.append(
                f"- `{issue.get('kind')}` entry {issue.get('entry_id')} "
                f"{issue.get('method')} {issue.get('path')} "
                f"status={issue.get('status')}"
            )
        lines.append("")

    walls = brief.get("walls") or {}
    if walls.get("hit_count"):
        lines.append("## Bot walls")
        lines.append("")
        lines.append(f"- Count: {walls.get('hit_count')} by_kind={walls.get('by_kind')}")
        for hit in walls.get("sample") or []:
            lines.append(
                f"- entry {hit.get('entry_id')} {hit.get('method')} "
                f"{hit.get('path')} kinds={hit.get('kinds')}"
            )
        lines.append("")

    lines.append("## Next")
    lines.append("")
    lines.append(brief.get("next") or "")
    lines.append("")

    path = Path(output_path)
    from hardly.core.pathguard import guard_write

    guard_write(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
    return {
        "output_path": str(path.resolve()),
        "host": h,
        "step_count": brief.get("step_count"),
        "correlation_count": len(corrs),
    }
