"""Export a Postman Collection v2.1 from indexed endpoints."""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Any
from urllib.parse import urlencode

from hardly.core.redact import is_sensitive_key


def export_postman(
    conn: sqlite3.Connection,
    output_path: str | Path,
    *,
    host: str | None = None,
    exclude_noise: bool = True,
    max_endpoints: int = 200,
    name: str = "HAR-derived API",
) -> dict[str, Any]:
    """Write a Postman collection JSON (secrets as {{placeholders}})."""
    clauses = ["method != 'OPTIONS'"]
    params: list[Any] = []
    if host:
        clauses.append("host = ?")
        params.append(host.lower())
    if exclude_noise:
        clauses.append("is_noise = 0")
    where = " AND ".join(clauses)

    rows = conn.execute(
        f"""
        SELECT method, host, path_template, path, scheme, query_raw,
               MIN(entry_id) AS sample_id, COUNT(*) AS cnt
        FROM entries
        WHERE {where}
        GROUP BY method, host, path_template
        ORDER BY host, path_template, method
        LIMIT ?
        """,
        [*params, max_endpoints],
    ).fetchall()

    items: list[dict[str, Any]] = []
    for row in rows:
        sample = conn.execute(
            "SELECT * FROM entries WHERE entry_id = ?",
            (row["sample_id"],),
        ).fetchone()
        if not sample:
            continue
        url = f"{sample['scheme']}://{sample['host']}{sample['path']}"
        query = []
        if sample["query_raw"]:
            from urllib.parse import parse_qsl

            for k, v in parse_qsl(sample["query_raw"], keep_blank_values=True):
                query.append(
                    {
                        "key": k,
                        "value": (
                            f"{{{{{k}}}}}" if is_sensitive_key(k) else v
                        ),
                    }
                )
        headers = []
        for h in conn.execute(
            "SELECT name, value_redacted FROM headers "
            "WHERE entry_id = ? AND side = 'request'",
            (row["sample_id"],),
        ):
            lname = h["name"].lower()
            if lname in {"cookie", "authorization", "content-length", "host"}:
                continue
            headers.append({"key": h["name"], "value": h["value_redacted"] or ""})

        body_row = conn.execute(
            "SELECT preview_text, content_type FROM bodies "
            "WHERE entry_id = ? AND side = 'request'",
            (row["sample_id"],),
        ).fetchone()
        body = None
        if body_row and body_row["preview_text"]:
            ct = (body_row["content_type"] or "").lower()
            text = body_row["preview_text"]
            if "json" in ct or text.lstrip().startswith(("{", "[")):
                body = {"mode": "raw", "raw": text, "options": {"raw": {"language": "json"}}}
            else:
                from urllib.parse import parse_qsl

                body = {
                    "mode": "urlencoded",
                    "urlencoded": [
                        {
                            "key": k,
                            "value": (
                                f"{{{{{k}}}}}"
                                if is_sensitive_key(k)
                                or k.upper().startswith("__VIEWSTATE")
                                or "TOKEN" in k.upper()
                                else v
                            ),
                        }
                        for k, v in parse_qsl(text, keep_blank_values=True)[:40]
                    ],
                }

        items.append(
            {
                "name": f"{row['method']} {row['path_template']}",
                "request": {
                    "method": row["method"],
                    "header": headers,
                    "url": {
                        "raw": url + (("?" + urlencode({q['key']: q['value'] for q in query})) if query else ""),
                        "protocol": sample["scheme"],
                        "host": sample["host"].split("."),
                        "path": [p for p in sample["path"].split("/") if p],
                        "query": query,
                    },
                    **({"body": body} if body else {}),
                },
                "response": [],
            }
        )

    collection = {
        "info": {
            "name": name,
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
            "description": f"Generated by hardly from HAR ({host or 'all hosts'}).",
        },
        "item": items,
    }
    path = Path(output_path)
    from hardly.core.pathguard import guard_write

    guard_write(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(collection, indent=2), encoding="utf-8")
    return {
        "output_path": str(path.resolve()),
        "host": host,
        "item_count": len(items),
        "note": "Import into Postman; replace {{placeholders}} and cookies.",
    }
