"""Export API documentation as Markdown."""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Any

from hardly.core.redact import redact_body_text
from hardly.core.safe_json import safe_loads
from hardly.core.schema_infer import infer_schema


def _parse_json(text: str | None) -> Any | None:
    if not text:
        return None
    try:
        return safe_loads(text)
    except (json.JSONDecodeError, TypeError):
        return None


def export_markdown(
    conn: sqlite3.Connection,
    output_path: str | Path,
    *,
    host: str | None = None,
    exclude_noise: bool = True,
    max_endpoints: int = 200,
    body_chars: int = 3000,
) -> dict:
    """Write API.md for endpoints in the session."""
    clauses = ["1=1"]
    params: list[Any] = []
    if host:
        clauses.append("host = ?")
        params.append(host.lower())
    if exclude_noise:
        clauses.append("is_noise = 0")
    where = " AND ".join(clauses)

    endpoints = conn.execute(
        f"""
        SELECT method, host, path_template, COUNT(*) AS cnt,
               GROUP_CONCAT(DISTINCT status) AS statuses,
               MIN(entry_id) AS sample_id
        FROM entries
        WHERE {where}
        GROUP BY method, host, path_template
        ORDER BY host, path_template, method
        LIMIT ?
        """,
        params + [max_endpoints],
    ).fetchall()

    lines: list[str] = []
    title_host = host or "all hosts"
    lines.append(f"# API reference ({title_host})")
    lines.append("")
    lines.append("Generated by [hardly](https://github.com/) from a HAR capture.")
    lines.append("")
    lines.append(f"Endpoints documented: **{len(endpoints)}**")
    lines.append("")

    for ep in endpoints:
        lines.append(f"## `{ep['method']} {ep['host']}{ep['path_template']}`")
        lines.append("")
        lines.append(f"- Occurrences: {ep['cnt']}")
        lines.append(f"- Status codes: {ep['statuses']}")
        lines.append(f"- Sample entry_id: {ep['sample_id']}")
        lines.append("")

        sample_id = ep["sample_id"]
        entry = conn.execute(
            "SELECT * FROM entries WHERE entry_id = ?", (sample_id,)
        ).fetchone()
        if not entry:
            continue

        if entry["query_raw"]:
            lines.append(f"- Query: `{entry['query_raw']}`")
            lines.append("")

        headers = conn.execute(
            """
            SELECT name, value_redacted FROM headers
            WHERE entry_id = ? AND side = 'request'
            ORDER BY name
            """,
            (sample_id,),
        ).fetchall()
        interesting = [
            h
            for h in headers
            if h["name"].lower()
            in {
                "content-type",
                "accept",
                "authorization",
                "x-xsrf-token",
                "x-csrf-token",
                "x-legfi-site-id",
                "x-api-key",
                "origin",
                "referer",
            }
            or h["name"].lower().startswith("x-")
        ]
        if interesting:
            lines.append("**Request headers (sample, redacted):**")
            lines.append("")
            lines.append("```")
            for h in interesting:
                lines.append(f"{h['name']}: {h['value_redacted']}")
            lines.append("```")
            lines.append("")

        req_body = conn.execute(
            "SELECT preview_text FROM bodies WHERE entry_id = ? AND side = 'request'",
            (sample_id,),
        ).fetchone()
        resp_body = conn.execute(
            "SELECT preview_text FROM bodies WHERE entry_id = ? AND side = 'response'",
            (sample_id,),
        ).fetchone()

        if req_body and req_body["preview_text"]:
            rb = redact_body_text(req_body["preview_text"], max_chars=body_chars)
            lines.append("**Request body (sample, redacted):**")
            lines.append("")
            lines.append("```json" if rb.get("json") else "```")
            lines.append(rb["text"] or "")
            lines.append("```")
            lines.append("")

        lines.append(f"**Response status:** `{entry['status']}`")
        lines.append("")

        if resp_body and resp_body["preview_text"]:
            sb = redact_body_text(resp_body["preview_text"], max_chars=body_chars)
            lines.append("**Response body (sample, redacted):**")
            lines.append("")
            lines.append("```json" if sb.get("json") else "```")
            lines.append(sb["text"] or "")
            lines.append("```")
            lines.append("")

        # Schema from all samples for this endpoint
        samples_req = []
        samples_resp = []
        ep_clauses = ["e.method = ?", "e.host = ?", "e.path_template = ?"]
        ep_params: list[Any] = [ep["method"], ep["host"], ep["path_template"]]
        if exclude_noise:
            ep_clauses.append("e.is_noise = 0")
        sample_rows = conn.execute(
            f"""
            SELECT e.entry_id FROM entries e
            WHERE {" AND ".join(ep_clauses)}
            LIMIT 20
            """,
            ep_params,
        ).fetchall()
        for sr in sample_rows:
            for side, bucket in (("request", samples_req), ("response", samples_resp)):
                b = conn.execute(
                    "SELECT preview_text FROM bodies WHERE entry_id = ? AND side = ?",
                    (sr["entry_id"], side),
                ).fetchone()
                parsed = _parse_json(b["preview_text"] if b else None)
                if parsed is not None:
                    bucket.append(parsed)

        if samples_req:
            lines.append("**Inferred request schema:**")
            lines.append("")
            lines.append("```json")
            lines.append(json.dumps(infer_schema(samples_req), indent=2))
            lines.append("```")
            lines.append("")
        if samples_resp:
            lines.append("**Inferred response schema:**")
            lines.append("")
            lines.append("```json")
            lines.append(json.dumps(infer_schema(samples_resp), indent=2))
            lines.append("```")
            lines.append("")

    out = Path(output_path)
    from hardly.core.pathguard import guard_write

    guard_write(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    return {
        "path": str(out.resolve()),
        "endpoints": len(endpoints),
        "host": host,
    }
