"""Regenerate docs/tools.md from the MCP tool definitions in server.py (and docs/cli.md).

    python scripts/gen_tool_docs.py          # write docs/tools.md
    python scripts/gen_tool_docs.py --check  # exit 1 if the file is stale
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / "src" / "hardly" / "server.py"
OUT = ROOT / "docs" / "tools.md"

# Display order and grouping; tools not listed land in "Other".
GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Guide and server", ("guide_task_plan", "guide_mode", "guide_help", "server_status")),
    (
        "Sessions and HAR files",
        (
            "session_open", "session_list", "session_close", "write_session_copy", "har_file_check",
            "write_har_pruned", "write_har_scrubbed", "write_har_split", "write_har_merged",
        ),
    ),
    (
        "Browser",
        (
            "browser_capture_discover", "browser_start", "browser_stop", "capture_list", "browser_interact",
            "browser_inspect", "browser_run_steps", "write_screenshot", "session_plan_steps",
        ),
    ),
    (
        "Capture orientation",
        (
            "session_overview", "session_traffic_stats", "session_body_coverage", "session_report",
            "session_site_brief", "session_story", "session_timeline", "session_redirect_history",
            "session_issues", "session_duplicates", "session_slow_requests",
        ),
    ),
    (
        "Capture lookup",
        (
            "entry_search", "entry_get", "entry_around", "entry_initiators", "entry_compare",
            "entry_build_curl", "entry_body_query", "entry_outline", "entry_dependencies",
            "session_trace_value", "session_compare", "session_sql",
        ),
    ),
    (
        "API shape and technology",
        (
            "endpoint_list", "endpoint_schema", "endpoint_graphql", "endpoint_streams",
            "endpoint_pagination", "endpoint_arcgis", "tech_stack", "spec_contract_check",
        ),
    ),
    (
        "Pages, auth and gates",
        (
            "page_list", "page_forms", "page_ui", "page_embedded_routes", "page_tables", "auth_report",
            "gate_bot_protection",
        ),
    ),
    (
        "Live requests (send_*, confirm-gated)",
        (
            "send_entry", "send_entry_ablation", "send_entry_series", "send_site_crawl",
            "send_arcgis_explore", "send_redirect_walk", "send_catalog_verify",
        ),
    ),
    ("Write and build output", ("write_export", "client_build")),
    ("Target catalog", ("catalog_list", "write_catalog_record")),
)


def load() -> dict[str, tuple[str, str, str]]:
    tree = ast.parse(SERVER.read_text(encoding="utf-8"))
    tools: dict[str, tuple[str, str, str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or not node.name.startswith("hardly_"):
            continue
        args = node.args
        names = [a.arg for a in args.args]
        defaults = [None] * (len(names) - len(args.defaults)) + list(args.defaults)
        parts = []
        for name, default in zip(names, defaults):
            parts.append(name if default is None else f"{name}={ast.unparse(default)}")
        doc = ast.get_docstring(node) or ""
        first = " ".join(doc.split("\n\n")[0].split())
        tools[node.name.removeprefix("hardly_")] = (", ".join(parts), first, doc)
    return tools


def render() -> str:
    tools = load()
    lines = [
        "# MCP tool reference",
        "",
        "Generated by `python scripts/gen_tool_docs.py` from `server.py` docstrings —",
        "edit the docstring, not this file. Every tool is prefixed `hardly_`. The first token tells",
        "the effect: `send_` sends network requests (confirm-gated: without `confirm=true` it returns a",
        "plan), `write_` writes a file (refuses to overwrite unless `overwrite=true`), `browser_` drives",
        "or reads a real browser; every other tool only reads loaded data. Merged tools take a",
        "`sections` list. `tests/api_surface.json` pins names and parameters.",
        "",
    ]
    seen: set[str] = set()
    sections = list(GROUPS)
    rest = tuple(sorted(set(tools) - {n for _, g in GROUPS for n in g}))
    if rest:
        sections.append(("Capture and other", rest))
    for title, names in sections:
        present = [n for n in names if n in tools]
        if not present:
            continue
        lines += [f"## {title}", ""]
        for name in present:
            sig, first, _ = tools[name]
            seen.add(name)
            lines.append(f"### `hardly_{name}({sig})`")
            lines += ["", first or "_No description._", ""]
    return "\n".join(lines).rstrip() + "\n"


SKILL_REFS = ("cheatsheet", "concepts", "sdk-workflow", "capture", "gate-policy", "reporting", "tools", "cli")
REFS_DIR = ROOT / "skills" / "hardly" / "references"


def refs_current() -> bool:
    """True when skills/hardly/references/*.md match docs/*.md."""
    return all(
        (REFS_DIR / f"{n}.md").exists()
        and (REFS_DIR / f"{n}.md").read_text(encoding="utf-8")
        == (ROOT / "docs" / f"{n}.md").read_text(encoding="utf-8")
        for n in SKILL_REFS
    )


def sync_refs() -> None:
    REFS_DIR.mkdir(parents=True, exist_ok=True)
    for n in SKILL_REFS:
        text = (ROOT / "docs" / f"{n}.md").read_text(encoding="utf-8")
        (REFS_DIR / f"{n}.md").write_text(text, encoding="utf-8")


def main() -> int:
    sys.path.insert(0, str(ROOT / "scripts"))
    import gen_cli_docs

    text = render()
    if "--check" in sys.argv:
        fresh = OUT.exists() and OUT.read_text(encoding="utf-8") == text
        return 0 if fresh and gen_cli_docs.main_check() else 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    gen_cli_docs.OUT.write_text(gen_cli_docs.render(), encoding="utf-8")
    sync_refs()
    print(f"wrote {OUT} ({text.count('### ')} tools) and skills/hardly/references")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
