"""Regenerate docs/tools.md from the MCP tool definitions in server.py.

    python scripts/gen_tool_docs.py          # write docs/tools.md
    python scripts/gen_tool_docs.py --check  # exit 1 if the file is stale
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / "src" / "hardly" / "server.py"
OUT = ROOT / "docs" / "tools.md"

# Display order and grouping; tools not listed land in "Other".
GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Orientation", ("start", "modes", "mode", "capabilities", "help", "recommend", "report")),
    ("Sessions", ("open", "reopen", "list_sessions", "close", "summary", "stats", "coverage")),
    ("Endpoints and content", ("streams", "body_query", "contract_check", "hosts", "endpoints", "content", "search", "entry", "compare_entries", "flow", "schema", "pages", "grids", "data_attrs", "arcgis")),
    ("HTML, forms and labels", ("brief", "story", "forms", "ui", "outline", "routes", "around", "tree", "params", "find_search", "stack", "tables", "auth_patterns", "pagination")),
    ("HAR hygiene", ("har_doctor", "har_prune", "har_split", "har_merge", "har_scrub")),
    ("Credentials and auth", ("credentials", "auth", "challenges", "correlate", "trace", "cookies", "secrets", "redirects")),
    ("APIs", ("graphql",)),
    ("Quality and traffic", ("issues", "wall", "duplicates", "slow", "diff", "gates")),
    ("Client SDK output", ("stub", "recipe_plan", "curl", "export_md", "export_openapi", "export_postman", "export_brief", "sql")),
    ("Live probe", ("flow_graph", "flow_replay", "probe", "arcgis_explore", "crawl", "redirect_diag", "replay_check")),
    ("Target catalog", ("catalog_list", "catalog_upsert", "catalog_verify")),
)


def load() -> dict[str, tuple[str, str, str]]:
    tree = ast.parse(SERVER.read_text(encoding="utf-8"))
    tools: dict[str, tuple[str, str, str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef) or not node.name.startswith("hardly_"):
            continue
        args = node.args
        names = [a.arg for a in args.args]
        defaults = [None] * (len(names) - len(args.defaults)) + list(args.defaults)
        parts = []
        for name, default in zip(names, defaults):
            parts.append(name if default is None else f"{name}={ast.unparse(default)}")
        doc = ast.get_docstring(node) or ""
        first = " ".join(doc.split("\n\n")[0].split())
        tools[node.name.removeprefix("hardly_")] = (", ".join(parts), first, doc)
    return tools


def render() -> str:
    tools = load()
    lines = [
        "# MCP tool reference",
        "",
        "Generated by `python scripts/gen_tool_docs.py` from `server.py` docstrings —",
        "edit the docstring, not this file. Every tool is prefixed `hardly_` over MCP;",
        "most also exist as `hardly <name-with-dashes>` on the CLI.",
        "",
    ]
    seen: set[str] = set()
    sections = list(GROUPS)
    rest = tuple(sorted(set(tools) - {n for _, g in GROUPS for n in g}))
    if rest:
        sections.append(("Capture and other", rest))
    for title, names in sections:
        present = [n for n in names if n in tools]
        if not present:
            continue
        lines += [f"## {title}", ""]
        for name in present:
            sig, first, _ = tools[name]
            seen.add(name)
            lines.append(f"### `hardly_{name}({sig})`")
            lines += ["", first or "_No description._", ""]
    return "\n".join(lines).rstrip() + "\n"


SKILL_REFS = ("cheatsheet", "concepts", "sdk-workflow", "capture", "gate-policy", "reporting", "tools")
REFS_DIR = ROOT / "skills" / "hardly" / "references"


def refs_current() -> bool:
    """True when skills/hardly/references/*.md match docs/*.md."""
    return all(
        (REFS_DIR / f"{n}.md").exists()
        and (REFS_DIR / f"{n}.md").read_text(encoding="utf-8")
        == (ROOT / "docs" / f"{n}.md").read_text(encoding="utf-8")
        for n in SKILL_REFS
    )


def sync_refs() -> None:
    REFS_DIR.mkdir(parents=True, exist_ok=True)
    for n in SKILL_REFS:
        text = (ROOT / "docs" / f"{n}.md").read_text(encoding="utf-8")
        (REFS_DIR / f"{n}.md").write_text(text, encoding="utf-8")


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        return 0 if OUT.exists() and OUT.read_text(encoding="utf-8") == text else 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    sync_refs()
    print(f"wrote {OUT} ({text.count('### ')} tools) and skills/hardly/references")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
