"""Regenerate docs/cli.md from the real argparse parser.

    python scripts/gen_cli_docs.py          # write docs/cli.md
    python scripts/gen_cli_docs.py --check  # exit 1 if the file is stale

``scripts/gen_tool_docs.py`` calls this too, so one command regenerates all generated docs.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
OUT = ROOT / "docs" / "cli.md"

import dump_cli_surface as surf  # noqa: E402

HEAD = """\
# CLI reference

> Purpose: The `hardly` command-line grammar and every command, generated from the argparse parser.

Generated by `python scripts/gen_cli_docs.py` from `cli.py` - edit the parser, not this file.
`tests/cli_surface.json` pins every command path and flag; v1 command names are permanent
(`docs/api-stability.md`).

## Grammar

```
hardly <group> <command> [HAR] [positionals] [--flags]
```

1. **Command = tool name.** The path is the MCP tool name without `hardly_`, split at the first
   underscore, the rest joined with hyphens: `hardly_session_traffic_stats` is
   `hardly session traffic-stats`, `hardly_send_entry` is `hardly send entry`. The first word
   carries the effect: `send` sends requests, `write` writes a file, `browser` drives a browser;
   every other group only reads.
2. **First positional is the capture.** Where the tool takes `session_id`, the command takes a HAR
   file or a saved index (`hardly session open HAR -o OUT` saves one). Other inputs keep the
   tool's noun as the positional: `URL`, `CATALOG_PATH`, `SPEC_PATH`, `ENTRY_ID`,
   `OTHER_ENTRY_ID`, `METHOD`, `PATH_TEMPLATE`.
3. **Flags are the tool's parameter names** with hyphens: `--host`, `--limit`, `--offset`,
   `--sections`, `--timeout-seconds`, `--entry-id`. `-o/--output` is `output_path` (`--output-dir`
   for a directory, `-o/--har-output-path` for a browser recording). Writes refuse to replace a
   file unless `--overwrite`.
4. **Booleans.** A flag that defaults to false is `--flag`; one that defaults to true is
   `--flag` / `--no-flag` (`--exclude-noise`, `--redact`, `--respect-robots`).
5. **Lists and objects.** Lists are comma separated (`--sections quick,cookies`,
   `--entry-ids 12,14`). Objects are inline JSON (`--overrides '{"headers":{}}'`); step lists are a
   JSON file (`--steps FILE`, `browser run-steps FILE`).
6. **Live commands use one spelling: `--confirm`.** Every `send` command and
   `browser capture-discover` prints only a plan (`"sent": false`, exit 0) without it.
   There is no `--yes`. Live commands and browser URLs refuse loopback, private and metadata
   hosts (`host_not_allowed`); for your own test target put the global flag before the group:
   `hardly --allow-private-hosts send entry HAR 3 --confirm` (same as `HARDLY_ALLOW_PRIVATE_HOSTS=1`).
   Writes stay in the working directory, the temp directory or `HARDLY_WRITE_DIRS` (`path_not_allowed`).
7. **Output.** JSON on stdout; errors are JSON with `error` (and `code`/`hint` where known) and
   exit 1. `session report --format md` and `entry outline --markdown-only` print text.
8. **Exit codes.** 0 success; 1 the command reported an error; 2 invalid usage (argparse) and
   input errors of `write har-*` and `har file-check`, whose `--fail-on` can also exit non-zero
   on findings.
9. **Sessions** live for one process: each command opens the HAR (or saved index) itself.

CLI-only commands, with no MCP tool of the same name: @CLI_ONLY@. The one tool without a command
is `hardly_session_close` (a process exits instead).

## Commands

| Command | Arguments | Flags | Mirrors | What it does |
|---|---|---|---|---|
"""


def _arg_cells(args: list[dict]) -> tuple[str, str]:
    pos: list[str] = []
    flags: list[str] = []
    for a in args:
        if a["kind"] == "positional":
            name = a["name"].upper()
            pos.append({"?": f"[{name}]", "*": f"[{name}...]", "+": f"{name}..."}.get(a["nargs"], name))
            continue
        long = next((f for f in a["flags"] if f.startswith("--") and not f.startswith("--no-")), a["flags"][-1])
        text = long
        if a["kind"] == "bool":
            text = long.replace("--", "--[no-]", 1)
        short = next((f for f in a["flags"] if not f.startswith("--")), None)
        if short:
            text = f"{short}/{text}"
        if a["required"]:
            text += "*"
        flags.append(f"`{text}`")
    return " ".join(f"`{p}`" for p in pos), " ".join(flags)


def render() -> str:
    rows = surf.surface()
    head = HEAD.replace("@CLI_ONLY@", ", ".join(f"`{c}`" for c in surf.CLI_ONLY))
    lines = [head.rstrip("\n")]
    for path, row in rows.items():
        pos, flags = _arg_cells(row["args"])
        tool = f"`{row['tool']}`" if row["tool"] else "CLI only"
        what = row["help"].replace("|", "/")
        lines.append(f"| `hardly {path}` | {pos} | {flags} | {tool} | {what} |")
    lines += ["", "`*` required flag. `--[no-]x` is a boolean that defaults to true.", ""]
    return "\n".join(lines)


def main_check() -> bool:
    return OUT.exists() and OUT.read_text(encoding="utf-8") == render()


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        return 0 if main_check() else 1
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
